export {default as Navbar} from "./NavBar/Navbar"
export {default as Products} from "./Products/Products"
export {default as ProductInfo} from "./Products/Product/ProductInfo"
export {default as MainPage} from "./Main/MainPage"
export {default as Checkout} from "./CheckoutForm/Checkout/Checkout"
export {default as Category} from "./Products/Product/Category/Category"
export {default as Footer} from "./Footer/Footer"
